---
- name: Nginx
  hosts: ubuntu
  become: true
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade all packages on servers
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started
